name: Farmer
author: Geik
main: xyz.geik.farmer.Main
version: 6b02
api-version: 1.13
softdepend: [BentoBox, Vault, ASkyBlock, SuperiorSkyblock2, GriefPrevention, FabledSkyBlock]
loadbefore: [AutoPickup, WildStacker]
commands:
  farmer:
    description: Main command of farmer
    aliases: [farm, çiftçi, fm, ciftci]